// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_total_receipts_10000 = "CgkI9oeOrd0IEAIQEQ"; // <GPGSID>
        public const string achievement_serving_girls__total_100_perfects = "CgkI9oeOrd0IEAIQLQ"; // <GPGSID>
        public const string achievement_reduce_complaints__less_than_3_complaints_in_3_game_plays = "CgkI9oeOrd0IEAIQNw"; // <GPGSID>
        public const string achievement_max_combo__40 = "CgkI9oeOrd0IEAIQOw"; // <GPGSID>
        public const string achievement_top_changes_15000 = "CgkI9oeOrd0IEAIQDQ"; // <GPGSID>
        public const string achievement_serving_couples__20_perfect_combos = "CgkI9oeOrd0IEAIQIA"; // <GPGSID>
        public const string achievement_max_visits_in_fever__45_visits = "CgkI9oeOrd0IEAIQQA"; // <GPGSID>
        public const string achievement_serving_beggars__10_perfect_combos = "CgkI9oeOrd0IEAIQGA"; // <GPGSID>
        public const string achievement_serving_balds_80__5_minutes = "CgkI9oeOrd0IEAIQJw"; // <GPGSID>
        public const string achievement_serving_kids__10_perfect_combos = "CgkI9oeOrd0IEAIQFA"; // <GPGSID>
        public const string achievement_sales_total_5000000 = "CgkI9oeOrd0IEAIQCA"; // <GPGSID>
        public const string achievement_goods_in_stock_29 = "CgkI9oeOrd0IEAIQLw"; // <GPGSID>
        public const string achievement_reduce_complaints__less_than_5_complaints_in_7_game_plays = "CgkI9oeOrd0IEAIQOA"; // <GPGSID>
        public const string achievement_max_combo__80 = "CgkI9oeOrd0IEAIQPQ"; // <GPGSID>
        public const string achievement_reduce_complaints__less_than_5_complaints_in_10_game_plays = "CgkI9oeOrd0IEAIQOQ"; // <GPGSID>
        public const string achievement_serving_girls__50_perfect_combos = "CgkI9oeOrd0IEAIQLA"; // <GPGSID>
        public const string leaderboard_top_score_ranking = "CgkI9oeOrd0IEAIQAQ"; // <GPGSID>
        public const string achievement_serving_kids__total_10 = "CgkI9oeOrd0IEAIQEg"; // <GPGSID>
        public const string achievement_serving_couples__total_50_perfects = "CgkI9oeOrd0IEAIQIQ"; // <GPGSID>
        public const string achievement_serving_beggars__total_50_perfects = "CgkI9oeOrd0IEAIQGQ"; // <GPGSID>
        public const string achievement_serving_balds_80__10_minutes = "CgkI9oeOrd0IEAIQJg"; // <GPGSID>
        public const string achievement_serving_balds_80__20_minutes = "CgkI9oeOrd0IEAIQJA"; // <GPGSID>
        public const string achievement_top_sales_50000 = "CgkI9oeOrd0IEAIQAg"; // <GPGSID>
        public const string achievement_serving_couples__5_combos = "CgkI9oeOrd0IEAIQHg"; // <GPGSID>
        public const string achievement_goods_in_stock_14 = "CgkI9oeOrd0IEAIQLg"; // <GPGSID>
        public const string achievement_serving_kids__5_perfect_combos = "CgkI9oeOrd0IEAIQEw"; // <GPGSID>
        public const string achievement_max_visits_in_fever__15_visits = "CgkI9oeOrd0IEAIQPg"; // <GPGSID>
        public const string achievement_max_combo__60 = "CgkI9oeOrd0IEAIQPA"; // <GPGSID>
        public const string achievement_sales_total_1000000 = "CgkI9oeOrd0IEAIQBw"; // <GPGSID>
        public const string achievement_serving_girls__10_combos = "CgkI9oeOrd0IEAIQKA"; // <GPGSID>
        public const string achievement_max_visits_in_fever__30_visits = "CgkI9oeOrd0IEAIQPw"; // <GPGSID>
        public const string achievement_total_receipts_500 = "CgkI9oeOrd0IEAIQDg"; // <GPGSID>
        public const string achievement_goods_in_stock_59 = "CgkI9oeOrd0IEAIQMQ"; // <GPGSID>
        public const string achievement_serving_girls__30_perfect_combos = "CgkI9oeOrd0IEAIQKw"; // <GPGSID>
        public const string achievement_top_changes_10000 = "CgkI9oeOrd0IEAIQDA"; // <GPGSID>
        public const string achievement_serving_girls__total_20_perfects = "CgkI9oeOrd0IEAIQKQ"; // <GPGSID>
        public const string achievement_serving_kids__20_perfect_combos = "CgkI9oeOrd0IEAIQFQ"; // <GPGSID>
        public const string achievement_serving_thief__10_perfect_combos = "CgkI9oeOrd0IEAIQHA"; // <GPGSID>
        public const string achievement_serving_beggars__total_10 = "CgkI9oeOrd0IEAIQFg"; // <GPGSID>
        public const string achievement_serving_couples__10_perfect_combos = "CgkI9oeOrd0IEAIQHw"; // <GPGSID>
        public const string achievement_serving_girls__15_perfect_combos = "CgkI9oeOrd0IEAIQKg"; // <GPGSID>
        public const string achievement_sales_total_15000000 = "CgkI9oeOrd0IEAIQCQ"; // <GPGSID>
        public const string achievement_serving_thief__total_50_perfects = "CgkI9oeOrd0IEAIQHQ"; // <GPGSID>
        public const string achievement_goods_in_stock_44 = "CgkI9oeOrd0IEAIQMA"; // <GPGSID>
        public const string achievement_serving_thief__total_10 = "CgkI9oeOrd0IEAIQGg"; // <GPGSID>
        public const string achievement_top_changes_5000 = "CgkI9oeOrd0IEAIQCw"; // <GPGSID>
        public const string achievement_top_changes_1000 = "CgkI9oeOrd0IEAIQCg"; // <GPGSID>
        public const string achievement_top_sales_1000000 = "CgkI9oeOrd0IEAIQBQ"; // <GPGSID>
        public const string achievement_serving_balds_80__30_minutes = "CgkI9oeOrd0IEAIQIw"; // <GPGSID>
        public const string achievement_total_receipts_1500 = "CgkI9oeOrd0IEAIQDw"; // <GPGSID>
        public const string achievement_serving_balds_80__in_an_hour = "CgkI9oeOrd0IEAIQIg"; // <GPGSID>
        public const string achievement_top_sales__600000 = "CgkI9oeOrd0IEAIQBA"; // <GPGSID>
        public const string achievement_serving_balds_80__15_minutes = "CgkI9oeOrd0IEAIQJQ"; // <GPGSID>
        public const string achievement_serving_thief__total_10_perfects = "CgkI9oeOrd0IEAIQGw"; // <GPGSID>
        public const string achievement_max_visits_in_fever__60_visits = "CgkI9oeOrd0IEAIQQQ"; // <GPGSID>
        public const string achievement_max_combo__20 = "CgkI9oeOrd0IEAIQOg"; // <GPGSID>
        public const string achievement_serving_beggars__total_10_perfects = "CgkI9oeOrd0IEAIQFw"; // <GPGSID>
        public const string achievement_top_sales_200000 = "CgkI9oeOrd0IEAIQAw"; // <GPGSID>
        public const string achievement_reduce_complaints__less_than_2_complaints_in_the_next_game_play = "CgkI9oeOrd0IEAIQNg"; // <GPGSID>
        public const string achievement_total_receipts_5000 = "CgkI9oeOrd0IEAIQEA"; // <GPGSID>
        public const string achievement_sales_total_100000 = "CgkI9oeOrd0IEAIQBg"; // <GPGSID>

}

